vich_uploader:
    db_driver: orm

    mappings:
        actualite_images:
            uri_prefix: '%kernel.project_dir%/public/imageAct'
            upload_destination: '%kernel.project_dir%/public/imageAct'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true